name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.AREKBEE_METRICS_TOKEN }}
          user: bnbsystems
          config_timezone: Europe/Warsaw
          plugin_achievements_limit: 0
          plugin_achievements_secrets: 'yes'
          plugin_activity: 'no'
          plugin_followup: 'yes'
          plugin_followup_sections: repositories, user
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          
          
          
          
