name: Metrics
on:
  schedule: [{cron: "0 0 1 * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.AREKBEE_METRICS_TOKEN }}
          user: bnbsystems
          config_timezone: Europe/Warsaw
          
          
          
          
