name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          config_timezone: Europe/Warsaw
          plugin_achievements: 'yes'
          plugin_achievements_limit: 0
          plugin_achievements_secrets: 'yes'
          plugin_activity: 'no'
          plugin_followup: 'yes'
          plugin_followup_sections: repositories, user
          plugin_languages: 'yes'
          plugin_languages_details: bytes-size, percentage
          plugin_notable: 'yes'
          plugin_notable_filter: stars:>1000
          plugin_notable_repositories: 'yes'
          plugin_stargazers: 'yes'
          plugin_habits: 'yes'
          plugin_habits_facts: 'yes'
          plugin_habits_charts: 'yes'
          plugin_contributors: 'yes'
          plugin_people: 'yes'
          
          
          
